### ISSUE TITLE
Loamy Grass, Rootydirt Makes Spectral Moss?

### ISSUE THREAD

**Issue by Exsolutus** [DynamicTreesTeam/DynamicTrees-BOP#25]
![2018-11-16_22 00 01](https://user-images.githubusercontent.com/23705866/48655888-88697880-e9eb-11e8-9d71-5870b72bdb65.png)

As seen in the image provided, Loamy Grass with roots shows up as Spectral Moss in HWYLA. Picking the block with Creative also results in Spectral Moss.

**Comment by supermassimo** [comment]
has been fixed
