### ISSUE TITLE
Crash - NoClassDefFoundError: dynamictreesbop/models/ModelLoaderBamboo

### ISSUE THREAD

**Issue by rinart73** [DynamicTreesTeam/DynamicTrees-BOP#39]
**Forge:** 1.12.2-14.23.5.2768
**Mod version:** 1.3.2
**Dynamic Trees version:** 0.9.4
**BOP version:** 7.0.1.2419
**Crashlog:** https://pastebin.com/r0B7Uqqx

**Comment by ferreusveritas** [comment]
Update the bop addon to the latest version
