### ISSUE TITLE
Crashes on launch due to bamboo model loading

### ISSUE THREAD

**Issue by tjeulink** [DynamicTreesTeam/DynamicTrees-BOP#40]
(i'm not sure if the issue here is the same as with #39 because i don't know if the causes of the crashes are different)
full crash log is here: https://pastebin.com/r1serzhE

**Comment by Graywaren** [comment]
I have also just had this issue

**Comment by tjeulink** [comment]
> 
> 
> I have also just had this issue using the released version of this mod.
> 
> I switched to the beta version of this mod, which required me to also get the beta of BOP. Doing this seems to have fixed the issue.

Ah okay, well its for my first modpack so i would have to wait until its pushed so i can include it in the twitch launcer automagically. i'll just test/develop the pack without it for now.
