### ISSUE TITLE
[Suggestion] Handle BoP fruit the same as apples

### ISSUE THREAD

**Issue by segabl** [DynamicTreesTeam/DynamicTrees-BOP#44]
Setting ``enableAppleTrees=true`` in the Dynamic Tree config creates dedicated apple trees instead of randomly spawning apples from oak and dark oak trees. Biomes O Plenty adds its own fruit, like persimmons and pears which also drop randomly from trees that don't really make sense. Maybe you could use the original config option to do the same for BoP fruit? Would be pretty nice since players could create dedicated orachands that way.

**Comment by supermassimo** [comment]
feature has been added
