### ISSUE TITLE
BOP update 2442 break the latest DY-BOP add-on

### ISSUE THREAD

**Issue by archonsd** [DynamicTreesTeam/DynamicTrees-BOP#49]
Can't update BOP to the latest or it breaks this add-on.

**Comment by eilamg** [comment]
Specifically,

![image](https://user-images.githubusercontent.com/4570254/67166537-42c4d680-f345-11e9-8e4c-070b8c527cc9.png)

**Comment by Random-nii-chan** [comment]
I get the same issue, I updated BOP yesterday and I get the same issue, even though the version of BOP I installed is the 2422 one.
![image](https://user-images.githubusercontent.com/32325398/67232817-691c6c00-f442-11e9-8e1d-a286ea8d76fa.png)

**Comment by eilamg** [comment]
Issue fixed by new BOP release (BiomesOPlenty-1.12.2-7.0.1.2443-universal.jar).
