### ISSUE TITLE
Dynamic Trees and BOP not compatible versions

### ISSUE THREAD

**Issue by SMcMenu** [DynamicTreesTeam/DynamicTrees-BOP#50]
Hi,

I have Minecraft on version 1.12.2, the one that works with most of the mods I want for my server. I've installed a bunch of mods and all worked fine. But a few hours ago I installed another bunch and got an error that didnt let me open the game, it crashed. After a short research I've found that the problem was on Dynamic Trees, BOP and their compatibility mod. I have the newest version of all three (DynamicTrees-1.12.2-0.9.7 / BiomesOPlenty-1.12.2-7.0.1.2444-universal / DynamicTreesBOP-1.12.2-1.4.1e). It seems that the newest versions doesnt match at all. Which versions of each mod can I use in order to dont crash my game?

Thanks in advance

**Comment by ferreusveritas** [comment]
I using those exact versions for DT, DTBop and BoP and it works fine.  Can you send the error?

**Comment by ubuntu811** [comment]
I'm having a crash specifically with BOP palmtrees:
(As in game goes into a crash loop whenever I get too close to tropical biomes) :)

-- Block model being tesselated --
Details:
	Block: dynamictreesbop:leaves_palm[hydro=1,tree=0]
	Block location: World: (-2292,76,918), Chunk: (at 12,4,6 in -144,57; contains blocks -2304,0,912 to -2289,255,927), Region: (-5,1; contains chunks -160,32 to -129,63, blocks -2560,0,512 to -2049,255,1023)
	Using AO: false
Stacktrace:
	at net.minecraft.client.renderer.BlockModelRenderer.func_187493_a(BlockModelRenderer.java:47)
	at net.minecraft.client.renderer.BlockModelRenderer.func_178267_a(BlockModelRenderer.java:38)

Can provide the full crashlog if needed. 

Versions:
	| LCHIJA | biomesoplenty         | 7.0.1.2441                   | BiomesOPlenty-1.12.2-7.0.1.2441-universal.jar                  | None                                     |
	| LCHIJA | dynamictrees          | 1.12.2-0.9.7                 | DynamicTrees-1.12.2-0.9.7.jar                                  | None                                     |
	| LCHIJA | dynamictreesbop       | 1.12.2-1.4.1e                | DynamicTreesBOP-1.12.2-1.4.1e.jar                              | None                                     |

BTW:
Is there any way to specifically disable one type of tree in dynamictrees, so that I can at least keep the rest of them loaded?

**Comment by ferreusveritas** [comment]
We really need the complete crash log so we can evaluate if interactions with other mods are potentially causing the problem.  Hundreds of thousands of people play with this set of mods with these exact versions(including myself) and it works perfectly.  So obviously you've got something special going on.  Best to include as much information as you can.  Use pastebin or similar for the crashlog.  As it stands this issue has provided us with no useful information other than "It doesn't work, plz fix".

**Comment by ubuntu811** [comment]
Enjoy :)
https://pastebin.com/dGD7QnmG

Whenever I port to a biome with palmtrees it dies.

**Comment by supermassimo** [comment]
has been fixed
