### ISSUE TITLE
Certain tree varieties dropping incorrect seeds

### ISSUE THREAD

**Issue by JMBarber** [DynamicTreesTeam/DynamicTrees-BOP#56]
I've noticed this problem chiefly in the Seasonal Forest biome: trees which use vanilla wood types seem to be dropping seeds based on their wood rather than their leaves (which are modded blocks), and sometimes even growing with a weird patchwork of two different leaf block types.  Autumnal Birch trees drop regular birch catkins, Autumnal Oaks drop dark oak acorns, and Maples drop oak acorns.

Notably, this only seems to occur with trees I plant myself, or which plant themselves from dropped seeds.  The trees initially placed during world generation drop the correct seeds.

**Comment by supermassimo** [comment]
should already be fixed
