### ISSUE TITLE
Flowering Oak Trees sometimes not dynamic

### ISSUE THREAD

**Issue by CalaMariGold** [DynamicTreesTeam/DynamicTrees-BOP#57]
![image](https://user-images.githubusercontent.com/57605926/101269459-1e8caa80-373d-11eb-9b9b-94a59f32e629.png)

Occurs in the Flower Forest. Only happens sometimes.
Let me know what information I could provide that would be useful.

**Comment by mossjones** [comment]
I think the issue is that specific type of tree because I just reported an issue with that exact tree except it was in the Sacred Springs instead of the Flower Forest.
![Screenshot_8](https://user-images.githubusercontent.com/49288710/101395083-70e1de80-3897-11eb-96e4-59d06f351ec1.png)

**Comment by supermassimo** [comment]
Duplicate of https://github.com/DynamicTreesTeam/DynamicTrees-BOP/issues/54
