### ISSUE TITLE
Sacred Springs Biome 

### ISSUE THREAD

**Issue by mossjones** [DynamicTreesTeam/DynamicTrees-BOP#58]
Trees in the Sacred Springs Biome aren't dynamic.
Temp, work around. (Just disable the biome in BoP settings)

The Picture below is an example of a Dynamic Jungle Biome next to a non-dynamic Sacred Springs Biome.
![Screenshot_8](https://user-images.githubusercontent.com/49288710/101394169-214ee300-3896-11eb-9eab-1047f1674764.png)

**Comment by KenyMylankca** [comment]
yeah, please fix this.

**Comment by supermassimo** [comment]
I will take a look!

**Comment by KenyMylankca** [comment]
thanks a lot! btw we're on 1.12.2

**Comment by KenyMylankca** [comment]
still nothing? :/

**Comment by supermassimo** [comment]
Duplicate of https://github.com/DynamicTreesTeam/DynamicTrees-BOP/issues/54
